//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSD.TaskCloud.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskCloudEntities : DbContext
    {
        public TaskCloudEntities()
            : base("name=TaskCloudEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActionCode> ActionCode { get; set; }
        public DbSet<AppSettings> AppSettings { get; set; }
        public DbSet<Attachment> Attachment { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Conversation> Conversation { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<EmailRequest> EmailRequest { get; set; }
        public DbSet<Permission> Permission { get; set; }
        public DbSet<Personnel> Personnel { get; set; }
        public DbSet<PriorityType> PriorityType { get; set; }
        public DbSet<PrivacyType> PrivacyType { get; set; }
        public DbSet<Profession> Profession { get; set; }
        public DbSet<ProxyUser> ProxyUser { get; set; }
        public DbSet<ResultType> ResultType { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<SMSRequest> SMSRequest { get; set; }
        public DbSet<StateType> StateType { get; set; }
        public DbSet<TaskCategory> TaskCategory { get; set; }
        public DbSet<TaskCodeType> TaskCodeType { get; set; }
        public DbSet<TaskPersonnel> TaskPersonnel { get; set; }
        public DbSet<TaskRequest> TaskRequest { get; set; }
        public DbSet<TaskResponse> TaskResponse { get; set; }
        public DbSet<TaskTemplate> TaskTemplate { get; set; }
        public DbSet<TaskType> TaskType { get; set; }
        public DbSet<Title> Title { get; set; }
        public DbSet<UserCalender> UserCalender { get; set; }
        public DbSet<UserSettings> UserSettings { get; set; }
        public DbSet<UserSignImg> UserSignImg { get; set; }
        public DbSet<WorkCalender> WorkCalender { get; set; }
        public DbSet<Task> Task { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<Reference> Reference { get; set; }
        public DbSet<TaskReference> TaskReference { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
