//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Collections;
using System.Linq; 
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Script.Serialization;


namespace WSD.TaskCloud.Contracts.EF
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Task))]
    [KnownType(typeof(Personnel))]
    public partial class TaskPersonnel: BaseEntityType,IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Simple Properties
    
    	[Key] //Fix++ : need to know key fields
        [DataMember]
        public System.Guid TaskPersonnelID
        {
            get { return _taskPersonnelID; }
            set
            {
               
    			//Fix++ :check current value
    		    if (!((value != null) && (_taskPersonnelID == value)))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'TaskPersonnelID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    //Fix++ : Property Validation
    				if (!isServerProcess)
    					if (!bIsCancelling)
    						if (this.ChangeTracker.State != ObjectState.Unchanged)
    							Validate(value, "TaskPersonnelID"); 
    						else
    						{
    							if (IsJustInitialized)	
    								Validate(value, "TaskPersonnelID"); 
    						}
                    _taskPersonnelID = value;
    				IsJustInitialized = false;
                    OnPropertyChanged("TaskPersonnelID");
                }
            }
        }
        private System.Guid _taskPersonnelID;
    
        [DataMember]
        public System.Guid TaskID
        {
            get { return _taskID; }
            set
            {
               
    			//Fix++ :check current value
    		    if (!((value != null) && (_taskID == value)))
                {
                    ChangeTracker.RecordOriginalValue("TaskID", _taskID);
                    if (!IsDeserializing)
                    {
                        if (Task != null && Task.TaskID != value)
                        {
                            Task = null;
                        }
                    }
                    //Fix++ : Property Validation
    				if (!isServerProcess)
    					if (!bIsCancelling)
    						if (this.ChangeTracker.State != ObjectState.Unchanged)
    							Validate(value, "TaskID"); 
    						else
    						{
    							if (IsJustInitialized)	
    								Validate(value, "TaskID"); 
    						}
                    _taskID = value;
    				IsJustInitialized = false;
                    OnPropertyChanged("TaskID");
                }
            }
        }
        private System.Guid _taskID;
    
        [DataMember]
        public int PersonnelID
        {
            get { return _personnelID; }
            set
            {
               
    			//Fix++ :check current value
    		    if (!((value != null) && (_personnelID == value)))
                {
                    ChangeTracker.RecordOriginalValue("PersonnelID", _personnelID);
                    if (!IsDeserializing)
                    {
                        if (Personnel != null && Personnel.PersonnelID != value)
                        {
                            Personnel = null;
                        }
                    }
                    //Fix++ : Property Validation
    				if (!isServerProcess)
    					if (!bIsCancelling)
    						if (this.ChangeTracker.State != ObjectState.Unchanged)
    							Validate(value, "PersonnelID"); 
    						else
    						{
    							if (IsJustInitialized)	
    								Validate(value, "PersonnelID"); 
    						}
                    _personnelID = value;
    				IsJustInitialized = false;
                    OnPropertyChanged("PersonnelID");
                }
            }
        }
        private int _personnelID;

        #endregion

        #region Navigation Properties
        [ScriptIgnore] //Fix++ circular reference exception 
        [DataMember]
        public Task Task
        {
            get { return _task; }
            set
            {
                if (!ReferenceEquals(_task, value))
                {
                    var previousValue = _task;
                    _task = value;
                    FixupTask(previousValue);
                    OnNavigationPropertyChanged("Task");
                }
            }
        }
        private Task _task;
        [ScriptIgnore] //Fix++ circular reference exception 
        [DataMember]
        public Personnel Personnel
        {
            get { return _personnel; }
            set
            {
                if (!ReferenceEquals(_personnel, value))
                {
                    var previousValue = _personnel;
                    _personnel = value;
                    FixupPersonnel(previousValue);
                    OnNavigationPropertyChanged("Personnel");
                }
            }
        }
        private Personnel _personnel;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Task = null;
            Personnel = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupTask(Task previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TaskPersonnel.Contains(this))
            {
                previousValue.TaskPersonnel.Remove(this);
            }
    
            if (Task != null)
            {
                Task.TaskPersonnel.Add(this);
    
                TaskID = Task.TaskID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Task")
                    && (ChangeTracker.OriginalValues["Task"] == Task))
                {
                    ChangeTracker.OriginalValues.Remove("Task");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Task", previousValue);
                }
                if (Task != null && !Task.ChangeTracker.ChangeTrackingEnabled)
                {
                    Task.StartTracking();
                }
            }
        }
    
        private void FixupPersonnel(Personnel previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TaskPersonnel.Contains(this))
            {
                previousValue.TaskPersonnel.Remove(this);
            }
    
            if (Personnel != null)
            {
                Personnel.TaskPersonnel.Add(this);
    
                PersonnelID = Personnel.PersonnelID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Personnel")
                    && (ChangeTracker.OriginalValues["Personnel"] == Personnel))
                {
                    ChangeTracker.OriginalValues.Remove("Personnel");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Personnel", previousValue);
                }
                if (Personnel != null && !Personnel.ChangeTracker.ChangeTrackingEnabled)
                {
                    Personnel.StartTracking();
                }
            }
        }

        #endregion

    }
}
